apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: app-dev-manju-ml-sales-prediction
spec:
  template:
    spec:
      containers:
      - image: app
        resources:
          limits:
            cpu: 1000m
            memory: 128Mi
